### ISSUE TITLE
Yu-gi-oh has horrifying visage

### ISSUE THREAD

**Issue by DaveTCode** [DaveTCode/GBADotnet#73]
![image](https://user-images.githubusercontent.com/1358414/162641286-84c16f32-54af-4664-97fd-ed34c7719a15.png)

That's horrific!

This is running mode 4 full 8 bit bitmaps with objects enabled. The only actual use of sprites here is for the central chars eyes though so they really shouldn't be causing this. Could still be a bitmap + obj issue since that's not a well tested thing

**Comment by DaveTCode** [comment]
Turning sprites off gets me 
![image](https://user-images.githubusercontent.com/1358414/162641489-c4a9a5c4-819a-44c6-867b-a06adc7b8f80.png)

which suggests sprite rendering effects things but more likely there's something funny with ppu registers or something of that sort

**Comment by ITotalJustice** [comment]
fwiw, without objects at all, the screen should look like this
![image](https://user-images.githubusercontent.com/47043333/163019751-8b3f628a-ba31-4379-a325-46dd0c4a642b.png)

**Comment by DaveTCode** [comment]
![image](https://user-images.githubusercontent.com/1358414/163143351-9418ea72-02dc-41bd-8417-d31d7d4b39c6.png)

Fixed, turns out that this game sets DISPCNT up so that all backgrounds are enabled but then renders in mode 4. In the spirit of writing bad code I was not handling this case well, the residual data left in bg0 scanline buffer was still there and my bg priority handling code deliberately doesn't care about which bgs are enabled.

Anyway, just clear the scanline buffers during start of scanline rendering to resolve.
